import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { AnalyticsSummary } from '@/hooks/useAnalytics';

export class PdfGeneratorService {
    static async generateAnalyticsReport(data: AnalyticsSummary, userName: string) {
        const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
            h1 { color: #6C63FF; font-size: 32px; margin-bottom: 5px; }
            .header { border-bottom: 2px solid #EEE; padding-bottom: 20px; margin-bottom: 30px; }
            .user-info { color: #888; font-size: 14px; }
            .stats-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 40px; }
            .stat-card { background: #F8F9FF; padding: 20px; border-radius: 12px; border: 1px solid #E0E4FF; }
            .stat-label { font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 1px; }
            .stat-value { font-size: 24px; font-weight: bold; color: #333; margin-top: 5px; }
            .section-title { font-size: 20px; font-weight: bold; margin-bottom: 15px; border-left: 4px solid #6C63FF; padding-left: 10px; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
            th { text-align: left; padding: 12px; background: #6C63FF; color: white; }
            td { padding: 12px; border-bottom: 1px solid #EEE; }
            .footer { margin-top: 50px; text-align: center; color: #AAA; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Habit Report</h1>
            <div class="user-info">Generated for ${userName} on ${new Date().toLocaleDateString()}</div>
          </div>

          <div class="section-title">Performance Summary</div>
          <div class="stats-grid">
            <div class="stat-card">
              <div class="stat-label">Avg Completion Rate</div>
              <div class="stat-value">${data.avgCompletionRate}%</div>
            </div>
            <div class="stat-card">
              <div class="stat-label">Longest Streak</div>
              <div class="stat-value">${data.bestStreak} Days</div>
            </div>
            <div class="stat-card">
              <div class="stat-label">Total Completions</div>
              <div class="stat-value">${data.totalCompletions}</div>
            </div>
            <div class="stat-card">
              <div class="stat-label">Active Habits</div>
              <div class="stat-value">${data.activeHabits}</div>
            </div>
          </div>

          <div class="section-title">Weekly Breakdown</div>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Day</th>
                <th>Completion Rate</th>
                <th>Steps</th>
              </tr>
            </thead>
            <tbody>
              ${data.weeklyData.map((day: any) => `
                <tr>
                  <td>${new Date(day.date).toLocaleDateString()}</td>
                  <td>${['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][new Date(day.date).getDay()]}</td>
                  <td>${day.rate}%</td>
                  <td>${day.steps.toLocaleString()}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            Generated by Antigravity Habit Tracker
          </div>
        </body>
      </html>
    `;

        try {
            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } catch (error) {
            console.error('PDF Generation Error:', error);
            throw error;
        }
    }
}
